spring.application.name=curso

#Porta do servidor
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/api_cursos_comunitarios
spring.datasource.username=postgres
spring.datasource.password=admin

#DDL - como o hibernate trata a estrutura do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

#SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Se houver campo extra no corpo da requisição, retorna 400 bad request
spring.jackson.deserialization.fail-on-unknown-properties=true

# Swagger/OpenAPI Configuração
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
